# Generated by Django 4.2.11 on 2024-05-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='estimatedTimeOfDeoarture',
            field=models.TimeField(null=True),
        ),
    ]
